# Script de configuracao automatica de IPs do Cloudflare no FortiGate
# Gerado em: 02/06/2026 04:39:38

config firewall address
    edit "Cloudflare_IPv4_1"
        set subnet 173.245.48.0/20
    next
    edit "Cloudflare_IPv4_2"
        set subnet 103.21.244.0/22
    next
    edit "Cloudflare_IPv4_3"
        set subnet 103.22.200.0/22
    next
    edit "Cloudflare_IPv4_4"
        set subnet 103.31.4.0/22
    next
    edit "Cloudflare_IPv4_5"
        set subnet 141.101.64.0/18
    next
    edit "Cloudflare_IPv4_6"
        set subnet 108.162.192.0/18
    next
    edit "Cloudflare_IPv4_7"
        set subnet 190.93.240.0/20
    next
    edit "Cloudflare_IPv4_8"
        set subnet 188.114.96.0/20
    next
    edit "Cloudflare_IPv4_9"
        set subnet 197.234.240.0/22
    next
    edit "Cloudflare_IPv4_10"
        set subnet 198.41.128.0/17
    next
    edit "Cloudflare_IPv4_11"
        set subnet 162.158.0.0/15
    next
    edit "Cloudflare_IPv4_12"
        set subnet 104.16.0.0/13
    next
    edit "Cloudflare_IPv4_13"
        set subnet 104.24.0.0/14
    next
    edit "Cloudflare_IPv4_14"
        set subnet 172.64.0.0/13
    next
    edit "Cloudflare_IPv4_15"
        set subnet 131.0.72.0/22
    next
    edit "Cloudflare_IPv6_1"
        set subnet6 2400:cb00::/32
    next
    edit "Cloudflare_IPv6_2"
        set subnet6 2606:4700::/32
    next
    edit "Cloudflare_IPv6_3"
        set subnet6 2803:f800::/32
    next
    edit "Cloudflare_IPv6_4"
        set subnet6 2405:b500::/32
    next
    edit "Cloudflare_IPv6_5"
        set subnet6 2405:8100::/32
    next
    edit "Cloudflare_IPv6_6"
        set subnet6 2a06:98c0::/29
    next
    edit "Cloudflare_IPv6_7"
        set subnet6 2c0f:f248::/32
    next
end

config firewall addrgrp
    edit "Group_Cloudflare_IPs"
        set member "Cloudflare_IPv4_1" "Cloudflare_IPv4_2" "Cloudflare_IPv4_3" "Cloudflare_IPv4_4" "Cloudflare_IPv4_5" "Cloudflare_IPv4_6" "Cloudflare_IPv4_7" "Cloudflare_IPv4_8" "Cloudflare_IPv4_9" "Cloudflare_IPv4_10" "Cloudflare_IPv4_11" "Cloudflare_IPv4_12" "Cloudflare_IPv4_13" "Cloudflare_IPv4_14" "Cloudflare_IPv4_15" "Cloudflare_IPv6_1" "Cloudflare_IPv6_2" "Cloudflare_IPv6_3" "Cloudflare_IPv6_4" "Cloudflare_IPv6_5" "Cloudflare_IPv6_6" "Cloudflare_IPv6_7"
    next
end
